### ISSUE TITLE
Option to bypass MVN by supplying jars manually

### ISSUE THREAD

**Issue by Egoscio** [wizawu/1c#7]
Hello,

First, I'd like to thank you for making this project. I've always wanted to bridge together TypeScript with the JVM.

All of my dependencies are custom built jar artifacts that aren't available through MVN. Could there please be an option to build type definitions from manually supplied jars rather than having to go through mvnRepositories? Thank you.

**Comment by wizawu** [comment]
Thank you.

I am quite surprised that so many people asked me about this project in the past week. I wonder where you guys heard about it, cuz I didn't advertise it recently. Anyway I am glad if it can help your development.

I just make some slight change to meet your requirement. As you know, `1c install` would create a directory `lib` and put all JARs downloaded from Maven here, and then generate `.d.ts` from them. Now you can create the `lib` on your own and put your JARs here before running `1c install`.

I am not sure if you want to separate these two kind of JARs in two directory (e.g. Maven in lib, yours in vendor), from the perspective of project management. In that case, a field named `jarDependencies` in `package.json` might be better?

**Comment by Egoscio** [comment]
I found out about this project while searching for a way to run TypeScript on the JVM via Nashorn. Initially, I was convinced that the only way to do this was to write my own type definition generator. Lo and behold, I found your implementation that's working very well.

I tried out 8.14.7 and it's working great. As for how project management goes with configuration and separating dependencies, I'm pretty flexible. I guess it would be a little redundant to have both a `jarDependencies` field and a separate folder. According to [this stack exchange post](https://softwareengineering.stackexchange.com/questions/123305/what-is-the-difference-between-the-lib-and-vendor-folders), `vendor` seems like a good name choice. Maybe upon running `1c install` you can generate both the `lib` and `vendor` preloaded with a README indicating their purpose. Just a though.

**Comment by wizawu** [comment]
I've tried a lot of languages, Erlang, Go, not to mention C++/Java/Python/JavaScript/Lua etc. I think Kotlin and TypeScript are designed in the most modern way. And TypeScript is the only language that can be used in both front-end and server-side (with V8 originally, but I don't like the callback style and there's no multi-threading). So I came up with the idea of running TypeScript on JVM.

Another purpose of this project is, I want to share source code between front-end and back-end. For example, when we implement `util.ts`, we can import it in both front-end and back-end source code instead of implementing these functions in Java/Go/Python again.
```typescript
// util.ts
export function isEmail(email: string) { ... }
export function generateID(input: string) { ... }
```

I don't like the idea of `jarDependencies` either. Maybe we can just keep it simple, `lib` for Java, `node_modules` for Node, for now.  #YAGNI#

Two more tips for you,
* If you are going to run many light processes with 1c, try OpenJ9. The footprint is 1/2 to 2/3 of Hotspot.
* If you are sure the TypeScript source code is written without syntax error, you can use `1c build --skipJDK` to skip checking TypeScript Definition of JDK, which can reduce a lot of compilation time.

Thank you again for sharing your use experience and interesting ideas.
